package:
  name: celltrack
  version: "0.1.3"

source:
# this is used for build from git hub
  git_rev: 0.1.3
  git_url: https://github.com/mjirik/celltrack.git

# this is used for pypi
  # fn: io3d-1.0.30.tar.gz
  # url: https://pypi.python.org/packages/source/i/io3d/io3d-1.0.30.tar.gz
  # md5: a3ce512c4c97ac2410e6dcc96a801bd8
#  patches:
   # List any patch files here
   # - fix.patch

build:
#  noarch: python
  ignore_prefix_files:
    - devel
    - examples
  # this is not necessary and not tested
#  always_include_files:
#    - celltrack/celltrack_icon512.png
#    - celltrack/celltrack_icon512.ico

  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - micrant = micrant:main
    #
    # Would create an entry point called io3d that calls micrant.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python 3.7
    - setuptools
    # - { pin_compatible('imma', max_pin='x.x') }
    - {{ pin_compatible('exsu', max_pin='x.x') }}
    - {{ pin_compatible('pandas', max_pin='x.x') }}
    - {{ pin_compatible('seaborn', max_pin='x.x') }}
    - {{ pin_compatible('pyqtgraph', max_pin='x.x') }}
    - {{ pin_compatible('io3d', max_pin='x.x') }}
    - {{ pin_compatible('scikit-image', max_pin='x.x') }}
    - click

  run:
    - python 3.7
    - {{ pin_compatible('exsu', max_pin='x.x') }}
    - {{ pin_compatible('pandas', max_pin='x.x') }}
    - {{ pin_compatible('seaborn', max_pin='x.x') }}
    - {{ pin_compatible('pyqtgraph', max_pin='x.x') }}
    - {{ pin_compatible('io3d', max_pin='x.x') }}
    - {{ pin_compatible('scikit-image', max_pin='x.x') }}
    - pywin32 # [win]
    - click
    # - numpy
    # - pyqt 4.11.* # [not win]
    # - pyqt 4.12.2 # [win]

test:
  # Python imports
  imports:
    - celltrack

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/mjirik/celltrack
  license: MIT
  summary: Cell tracking from microscopic data

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
